"""edited_tasks_db

Revision ID: 2ffd14b84142
Revises: e390efc28d2e
Create Date: 2023-11-25 23:19:12.507418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffd14b84142'
down_revision: Union[str, None] = 'e390efc28d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
