"""edited Role

Revision ID: 3832f632d8eb
Revises: 5667ac0c8ce9
Create Date: 2023-11-22 15:56:53.489519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3832f632d8eb'
down_revision: Union[str, None] = '5667ac0c8ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_email', table_name='role')
    op.drop_column('role', 'is_superuser')
    op.drop_column('role', 'is_verified')
    op.drop_column('role', 'email')
    op.drop_column('role', 'is_active')
    op.drop_column('role', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_role_email', 'role', ['email'], unique=False)
    # ### end Alembic commands ###
