"""Added_tasks_db

Revision ID: e390efc28d2e
Revises: 3832f632d8eb
Create Date: 2023-11-25 17:18:42.433017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e390efc28d2e'
down_revision: Union[str, None] = '3832f632d8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('finish_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
